---
abstract: 'Succinct options for Moose'
author:
  - 'Peter Shangov <pshangov@yahoo.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::More: 0
  Test::Most: 0
  namespace::autoclean: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Has-Options
requires:
  Carp: 0
  Package::Stash: 0.18
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=MooseX-Has-Options
  homepage: http://github.com/pshangov/moosex-has-options/tree
  repository: git://github.com/pshangov/moosex-has-options.git
version: 0.002
